name: CI

on:
  push:
    branches: [ AllexBookshelf ]
  pull_request:
    branches: [ AllexBookshelf ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Ensure Node.js version matches your project's requirements

      - name: Install npm dependencies
        run: npm install

      - name: Build the React frontend
        run: npm run build

      - name: Run Unit Tests and Coverage
        run: npm test -- --coverage --no-watch
      
      - name: Archive Coverage Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage-report
          path: coverage/ # Upload the coverage directory

      - name: Package the application
        run: ./gradlew packageApplication

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: distributions/bookshelf.zip

      - name: Clean up
        run: ./gradlew clean
